plugins {
    id 'java'
    id 'application'
}

group = 'com.flyingCatMan.automata'   // change this to your package base
version = '1.0'

application {
    mainClass = 'automata.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

tasks.named('run') {
    standardInput = System.in
}
tasks.named('test') {
    useJUnitPlatform()
}
